FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    nmap \
    curl \
    netcat-traditional \
    iputils-ping \
    python3 \
    procps \
    && rm -rf /var/lib/apt/lists/*

CMD ["tail", "-f", "/dev/null"]
